server:
  port: 3000

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  ws:
    endpoint: /ws-stomp
    topic: /topic/chatroom/global
    app-destination: /app
  redis:
    channel: chat
    rate-limit-per-minute: 10
  dynamodb:
    table-name: ${DYNAMODB_TABLE_NAME:chatapp-dev-messages}
    region: ${AWS_REGION:ap-northeast-2}
    ttl-seconds: 36000
    endpoint: ${DYNAMODB_ENDPOINT:}
    access-key: ${DYNAMODB_ACCESS_KEY:}
    secret-key: ${DYNAMODB_SECRET_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

