version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: chatapp-dev-task-green:1
        LoadBalancerInfo:
          ContainerName: chatapp-container
          ContainerPort: 3000
